export const indiaLocations = [
  // Major Metros
  { name: "Mumbai", type: "city", state: "Maharashtra", region: "West" },
  { name: "Delhi", type: "city", state: "Delhi", region: "North" },
  { name: "Bangalore", type: "city", state: "Karnataka", region: "South" },
  { name: "Hyderabad", type: "city", state: "Telangana", region: "South" },
  { name: "Chennai", type: "city", state: "Tamil Nadu", region: "South" },
  { name: "Kolkata", type: "city", state: "West Bengal", region: "East" },
  { name: "Pune", type: "city", state: "Maharashtra", region: "West" },
  { name: "Ahmedabad", type: "city", state: "Gujarat", region: "West" },
  
  // States
  { name: "Andhra Pradesh", type: "state", region: "South" },
  { name: "Arunachal Pradesh", type: "state", region: "Northeast" },
  { name: "Assam", type: "state", region: "Northeast" },
  { name: "Bihar", type: "state", region: "East" },
  { name: "Chhattisgarh", type: "state", region: "Central" },
  { name: "Goa", type: "state", region: "West" },
  { name: "Gujarat", type: "state", region: "West" },
  { name: "Haryana", type: "state", region: "North" },
  { name: "Himachal Pradesh", type: "state", region: "North" },
  { name: "Jharkhand", type: "state", region: "East" },
  { name: "Karnataka", type: "state", region: "South" },
  { name: "Kerala", type: "state", region: "South" },
  { name: "Madhya Pradesh", type: "state", region: "Central" },
  { name: "Maharashtra", type: "state", region: "West" },
  { name: "Manipur", type: "state", region: "Northeast" },
  { name: "Meghalaya", type: "state", region: "Northeast" },
  { name: "Mizoram", type: "state", region: "Northeast" },
  { name: "Nagaland", type: "state", region: "Northeast" },
  { name: "Odisha", type: "state", region: "East" },
  { name: "Punjab", type: "state", region: "North" },
  { name: "Rajasthan", type: "state", region: "North" },
  { name: "Sikkim", type: "state", region: "Northeast" },
  { name: "Tamil Nadu", type: "state", region: "South" },
  { name: "Telangana", type: "state", region: "South" },
  { name: "Tripura", type: "state", region: "Northeast" },
  { name: "Uttar Pradesh", type: "state", region: "North" },
  { name: "Uttarakhand", type: "state", region: "North" },
  { name: "West Bengal", type: "state", region: "East" },
  
  // Union Territories
  { name: "Andaman and Nicobar Islands", type: "union_territory", region: "South" },
  { name: "Chandigarh", type: "union_territory", region: "North" },
  { name: "Dadra and Nagar Haveli and Daman and Diu", type: "union_territory", region: "West" },
  { name: "Delhi", type: "union_territory", region: "North" },
  { name: "Jammu and Kashmir", type: "union_territory", region: "North" },
  { name: "Ladakh", type: "union_territory", region: "North" },
  { name: "Lakshadweep", type: "union_territory", region: "South" },
  { name: "Puducherry", type: "union_territory", region: "South" },
  
  // Major Cities
  { name: "Agra", type: "city", state: "Uttar Pradesh", region: "North" },
  { name: "Ajmer", type: "city", state: "Rajasthan", region: "North" },
  { name: "Aligarh", type: "city", state: "Uttar Pradesh", region: "North" },
  { name: "Allahabad (Prayagraj)", type: "city", state: "Uttar Pradesh", region: "North" },
  { name: "Amravati", type: "city", state: "Maharashtra", region: "West" },
  { name: "Amritsar", type: "city", state: "Punjab", region: "North" },
  { name: "Aurangabad", type: "city", state: "Maharashtra", region: "West" },
  { name: "Bareilly", type: "city", state: "Uttar Pradesh", region: "North" },
  { name: "Belgaum", type: "city", state: "Karnataka", region: "South" },
  { name: "Bhavnagar", type: "city", state: "Gujarat", region: "West" },
  { name: "Bhopal", type: "city", state: "Madhya Pradesh", region: "Central" },
  { name: "Bhubaneswar", type: "city", state: "Odisha", region: "East" },
  { name: "Bikaner", type: "city", state: "Rajasthan", region: "North" },
  { name: "Bokaro", type: "city", state: "Jharkhand", region: "East" },
  { name: "Chandigarh", type: "city", state: "Chandigarh", region: "North" },
  { name: "Coimbatore", type: "city", state: "Tamil Nadu", region: "South" },
  { name: "Cuttack", type: "city", state: "Odisha", region: "East" },
  { name: "Dehradun", type: "city", state: "Uttarakhand", region: "North" },
  { name: "Dhanbad", type: "city", state: "Jharkhand", region: "East" },
  { name: "Durgapur", type: "city", state: "West Bengal", region: "East" },
  { name: "Faridabad", type: "city", state: "Haryana", region: "North" },
  { name: "Ghaziabad", type: "city", state: "Uttar Pradesh", region: "North" },
  { name: "Guwahati", type: "city", state: "Assam", region: "Northeast" },
  { name: "Gwalior", type: "city", state: "Madhya Pradesh", region: "Central" },
  { name: "Hubli-Dharwad", type: "city", state: "Karnataka", region: "South" },
  { name: "Indore", type: "city", state: "Madhya Pradesh", region: "Central" },
  { name: "Jabalpur", type: "city", state: "Madhya Pradesh", region: "Central" },
  { name: "Jaipur", type: "city", state: "Rajasthan", region: "North" },
  { name: "Jalandhar", type: "city", state: "Punjab", region: "North" },
  { name: "Jamshedpur", type: "city", state: "Jharkhand", region: "East" },
  { name: "Jhansi", type: "city", state: "Uttar Pradesh", region: "North" },
  { name: "Jodhpur", type: "city", state: "Rajasthan", region: "North" },
  { name: "Kannur", type: "city", state: "Kerala", region: "South" },
  { name: "Kanpur", type: "city", state: "Uttar Pradesh", region: "North" },
  { name: "Kochi", type: "city", state: "Kerala", region: "South" },
  { name: "Kota", type: "city", state: "Rajasthan", region: "North" },
  { name: "Kozhikode", type: "city", state: "Kerala", region: "South" },
  { name: "Lucknow", type: "city", state: "Uttar Pradesh", region: "North" },
  { name: "Ludhiana", type: "city", state: "Punjab", region: "North" },
  { name: "Madurai", type: "city", state: "Tamil Nadu", region: "South" },
  { name: "Mangalore", type: "city", state: "Karnataka", region: "South" },
  { name: "Meerut", type: "city", state: "Uttar Pradesh", region: "North" },
  { name: "Moradabad", type: "city", state: "Uttar Pradesh", region: "North" },
  { name: "Mysore", type: "city", state: "Karnataka", region: "South" },
  { name: "Nagpur", type: "city", state: "Maharashtra", region: "West" },
  { name: "Nashik", type: "city", state: "Maharashtra", region: "West" },
  { name: "Navi Mumbai", type: "city", state: "Maharashtra", region: "West" },
  { name: "Noida", type: "city", state: "Uttar Pradesh", region: "North" },
  { name: "Patna", type: "city", state: "Bihar", region: "East" },
  { name: "Raipur", type: "city", state: "Chhattisgarh", region: "Central" },
  { name: "Rajkot", type: "city", state: "Gujarat", region: "West" },
  { name: "Ranchi", type: "city", state: "Jharkhand", region: "East" },
  { name: "Salem", type: "city", state: "Tamil Nadu", region: "South" },
  { name: "Shimla", type: "city", state: "Himachal Pradesh", region: "North" },
  { name: "Siliguri", type: "city", state: "West Bengal", region: "East" },
  { name: "Solapur", type: "city", state: "Maharashtra", region: "West" },
  { name: "Srinagar", type: "city", state: "Jammu and Kashmir", region: "North" },
  { name: "Surat", type: "city", state: "Gujarat", region: "West" },
  { name: "Thane", type: "city", state: "Maharashtra", region: "West" },
  { name: "Thiruvananthapuram", type: "city", state: "Kerala", region: "South" },
  { name: "Tiruchirappalli", type: "city", state: "Tamil Nadu", region: "South" },
  { name: "Tiruppur", type: "city", state: "Tamil Nadu", region: "South" },
  { name: "Udaipur", type: "city", state: "Rajasthan", region: "North" },
  { name: "Vadodara", type: "city", state: "Gujarat", region: "West" },
  { name: "Varanasi", type: "city", state: "Uttar Pradesh", region: "North" },
  { name: "Vijayawada", type: "city", state: "Andhra Pradesh", region: "South" },
  { name: "Visakhapatnam", type: "city", state: "Andhra Pradesh", region: "South" },
  { name: "Warangal", type: "city", state: "Telangana", region: "South" },
];

export const getLocationIcon = (type: string) => {
  switch(type) {
    case 'city':
      return '🏙️';
    case 'state':
      return '🏛️';
    case 'union_territory':
      return '🏢';
    default:
      return '📍';
  }
};
